"""fix offer

Revision ID: 97560cd6ee1f
Revises: f8596c4d2c54
Create Date: 2024-12-16 21:58:59.012887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97560cd6ee1f'
down_revision: Union[str, None] = 'f8596c4d2c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bestoffer',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('offer', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bestoffer')
    # ### end Alembic commands ###
